### ISSUE TITLE
WakeOnLan機能

### ISSUE THREAD

**Issue by P4sTela** [VirtualLiveLab/Mikubot#13]
## 部室内のサーバー上にbotおいたら部PCWoLできるくね？ってやつ。
ちなみに必要な理由としては、製作が忙しくなったらレンダリング等でリモートデスクトップに一定の需要がある。

---

## 概要

-

**Comment by sushichan044** [comment]
Synology NASから部室内LANに向かってMagic Packetを送れるようになったので、
そのサービスのAPIと接続することでDiscordからPCを遠隔起動できる

**Comment by sushichan044** [comment]
なお、OSSの適当なものを使っているのでAPI側はあとから書き直す必要がある
