### ISSUE TITLE
タイムスタンプ ユーティリティの追加

### ISSUE THREAD

**Issue by sushi-chaaaan** [VirtualLiveLab/Mikubot#93]

**Comment by 7AXEL** [comment]
Check out this project: https://github.com/7AXEL/Web2APK

**Comment by sushi-chaaaan** [comment]
DiscordメッセージにはPOSIX TIMESTAMPを埋め込めるが、手打ちが面倒なのでユーティリティを用意する
https://discord.com/developers/docs/reference#message-formatting-timestamp-styles

**Comment by sushi-chaaaan** [comment]
DiscordTimeStamp.to_discord_timestampはさすがに命名が良くない
